const express = require("express");
const jwt = require("jsonwebtoken");
const { body, validationResult } = require("express-validator");
const User = require("../models/User");
const MeetingType = require("../models/MeetingType");
const { auth } = require("../middleware/auth");

const router = express.Router();

// Register (tenant-aware: if mounted under /api/t/:slug, attach ownerAdmin)
router.post(
  "/register",
  [
    body("email").isEmail().withMessage("Please enter a valid email address"),
    body("password").isLength({ min: 8 }).withMessage("Password must be at least 8 characters"),
    body("firstName").trim().notEmpty().withMessage("First name is required"),
    body("lastName").trim().notEmpty().withMessage("Last name is required"),
  ],
  async (req, res) => {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        const errorMessages = errors.array().map(e => e.msg).join(", ");
        return res.status(400).json({ 
          error: errorMessages,
          errors: errors.array() 
        });
      }

      const { email, password, firstName, lastName, phone, timezone } =
        req.body;

      // Check if user already exists
      const existingUser = await User.findOne({ email });
      if (existingUser) {
        return res.status(400).json({ error: "User already exists" });
      }

      // Create new admin user
      // Registration is admin-only - clients don't need accounts
      const user = new User({
        email,
        password,
        firstName,
        lastName,
        phone,
        timezone: timezone || "UTC",
        role: "admin",
      });
      // Slug will be auto-generated by the User model pre-save hook

      await user.save();

      // Create default meeting types for admin users
      if (user.role === "admin") {
        const defaultMeetingTypes = [
          {
            name: "Quick Consultation",
            description: "30-minute consultation session",
            price: 50,
            currency: "GHS",
            duration: 30,
            color: "#1976d2",
            isActive: true,
            ownerAdmin: user._id,
          },
          {
            name: "Standard Meeting",
            description: "1-hour standard meeting",
            price: 100,
            currency: "GHS",
            duration: 60,
            color: "#2e7d32",
            isActive: true,
            ownerAdmin: user._id,
          },
          {
            name: "Extended Session",
            description: "90-minute extended session",
            price: 150,
            currency: "GHS",
            duration: 90,
            color: "#ed6c02",
            isActive: true,
            ownerAdmin: user._id,
          },
          {
            name: "Free Introduction",
            description: "15-minute free introductory call",
            price: 0,
            currency: "GHS",
            duration: 15,
            color: "#9c27b0",
            isActive: true,
            ownerAdmin: user._id,
          },
        ];

        await MeetingType.insertMany(defaultMeetingTypes);
      }

      // Generate JWT token
      const token = jwt.sign(
        { userId: user._id, email: user.email, role: user.role },
        process.env.JWT_SECRET,
        { expiresIn: "7d" }
      );

      res.status(201).json({
        message: "User registered successfully",
        token,
        user: {
          id: user._id,
          email: user.email,
          firstName: user.firstName,
          lastName: user.lastName,
          role: user.role,
          slug: user.slug,
        },
      });
    } catch (error) {
      console.error("Registration error:", error);
      res.status(500).json({ error: "Registration failed" });
    }
  }
);

// Login (optionally validate tenant scope if provided)
router.post(
  "/login",
  [
    body("email").isEmail().withMessage("Please enter a valid email address"),
    body("password").notEmpty().withMessage("Password is required"),
  ],
  async (req, res) => {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        // Return user-friendly error message
        const errorMessages = errors.array().map(e => e.msg).join(", ");
        return res.status(400).json({ 
          error: errorMessages,
          errors: errors.array() 
        });
      }

      const { email, password } = req.body;

      // Find user
      const user = await User.findOne({ email, isActive: true });
      if (!user) {
        return res.status(401).json({ error: "Invalid credentials" });
      }

      // Check password
      const isMatch = await user.comparePassword(password);
      if (!isMatch) {
        return res.status(401).json({ error: "Invalid credentials" });
      }

      // Only admins can log in
      if (user.role !== "admin") {
        return res.status(403).json({ error: "Access denied" });
      }

      // If tenant scope is present, ensure user is the admin of that tenant
      if (req.tenantAdminId) {
        const tenantId = req.tenantAdminId;
        if (user._id.toString() !== tenantId) {
          return res
            .status(403)
            .json({ error: "Wrong tenant for this account" });
        }
      }

      // Update last login
      user.lastLogin = new Date();
      await user.save();

      // Generate JWT token
      const token = jwt.sign(
        { userId: user._id, email: user.email, role: user.role },
        process.env.JWT_SECRET,
        { expiresIn: "7d" }
      );

      res.json({
        message: "Login successful",
        token,
        user: {
          id: user._id,
          email: user.email,
          firstName: user.firstName,
          lastName: user.lastName,
          role: user.role,
          slug: user.slug,
        },
      });
    } catch (error) {
      console.error("Login error:", error);
      res.status(500).json({ error: "Login failed" });
    }
  }
);

// Get current user
router.get("/me", auth, async (req, res) => {
  try {
    const user = await User.findById(req.user.userId).select("-password");
    if (!user) {
      return res.status(404).json({ error: "User not found" });
    }

    res.json({
      user: {
        id: user._id,
        email: user.email,
        firstName: user.firstName,
        lastName: user.lastName,
        role: user.role,
        phone: user.phone,
        timezone: user.timezone,
        slug: user.slug,
      },
    });
  } catch (error) {
    console.error("Get user error:", error);
    res.status(500).json({ error: "Failed to get user" });
  }
});

// Update user profile
router.put(
  "/profile",
  auth,
  [
    body("firstName").optional().trim().notEmpty(),
    body("lastName").optional().trim().notEmpty(),
    body("phone").optional().trim(),
    body("timezone").optional().trim(),
  ],
  async (req, res) => {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        return res.status(400).json({ errors: errors.array() });
      }

      const updates = {};
      const allowedUpdates = ["firstName", "lastName", "phone", "timezone"];

      allowedUpdates.forEach((field) => {
        if (req.body[field] !== undefined) {
          updates[field] = req.body[field];
        }
      });

      const user = await User.findByIdAndUpdate(req.user.userId, updates, {
        new: true,
        runValidators: true,
      }).select("-password");

      if (!user) {
        return res.status(404).json({ error: "User not found" });
      }

      res.json({
        message: "Profile updated successfully",
        user: {
          id: user._id,
          email: user.email,
          firstName: user.firstName,
          lastName: user.lastName,
          role: user.role,
          phone: user.phone,
          timezone: user.timezone,
        },
      });
    } catch (error) {
      console.error("Update profile error:", error);
      res.status(500).json({ error: "Failed to update profile" });
    }
  }
);

module.exports = router;
